version: '3.7'
services:
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - 8080:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      - /<path_to_jenkins_workspace>/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - rep:/media/nfs/jenkins
      - /<path_to_ssh_key>/id_rsa:/root/.ssh/id_rsa
    environment:
      - TZ=Asia/Taipei
volumes:
  rep :
    driver : "local"
    driver_opts:
      type : "cifs"
      o : "username=<username>,password=<password>,vers=1.0"
      device : "\\\\<host>\\Path\\to\\Jenkin"